config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  devise_for :users

  resources :restaurants do
    resources :baskets do
      resources :order_baskets, only: [:create, :destroy]
    end
    resources :products
  end

  resources :orders, only: [:show]

  get 'update_stock', to: 'baskets#update_stock', as: 'update_stock'

  get 'dashboard', to: 'restaurants#dashboard', as: 'dashboard'

end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :restaurant
  has_many :basket_products, dependent: :destroy
  has_many :products, through: :basket_products, dependent: :nullify
  has_many :order_baskets
  has_one_attached :photo
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  skip_before_action :authenticate_user!, only:[:index, :show]
  skip_after_action :verify_authorized, only:[:index]

  def index
    # Will match with the basket show page
    @baskets = policy_scope(Basket).order(created_at: :asc)
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def show
    @basket = Basket.find(params[:id])
    authorize @basket
  end

  def new
    @basket = Basket.new
    @restaurant = Restaurant.find(params[:restaurant_id])
    authorize @basket
  end

  def create
    @basket = Basket.new(params_baskets)
    @basket.restaurant = Restaurant.find(params[:restaurant_id])
    authorize @basket

    if @basket.save
      redirect_to restaurant_baskets_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @basket = Basket.find(params[:id])
    authorize @basket
    @basket.destroy
    redirect_to restaurant_baskets_path notice: "Bye bye #{@basket.name} basket"
  end

    def update_stock
    @basket = Basket.find(params[:basket_id])
    if params[:stock_update] == "increase"
      @basket.stock += 1
    else
      @basket.stock -= 1
    end
    @basket.save!
    authorize @basket
    redirect_to restaurant_baskets_path(@basket.restaurant)
  end

private

  def params_baskets
     params.require(:basket).permit(:name, :price, :description, :date, :stock, :restaurant_id, :photo, product_ids: [])
   end
end

app/views/baskets/create.html.erb
<h1>Baskets#create</h1>
<p>Find me in app/views/baskets/create.html.erb</p>

app/views/baskets/destroy.html.erb
<h1>Baskets#destroy</h1>
<p>Find me in app/views/baskets/destroy.html.erb</p>

app/views/baskets/edit.html.erb
<h1>Baskets#edit</h1>
<p>Find me in app/views/baskets/edit.html.erb</p>

app/views/baskets/index.html.erb
<%= render 'shared/navbar' %>

<div class="container">
<h1 class="basket-title">Baskets list</h1>

<% @baskets.each do |basket| %>
    <div class="card-basket">
     <% if basket.photo.attached? %>
              <%= cl_image_tag basket.photo.key %>
              <% else %>
              <%= cl_image_tag "https://res.cloudinary.com/dnie1qfbq/image/upload/v1583754005/basket2_tqfshn.jpg", height: 300, width: 400, crop: :fill %>
              <% end %>
        <div class="card-basket-infos">
        <h2><%= basket.name %></h2>


         <p><%= basket.description %></p>
          <p><%= basket.price %> €</p>
          <p><ul>
            <% basket.basket_products.each do |basket_product| %>
              <li><%= basket_product.product.name %></li>
            <% end %>
          </ul></p>

        </div>
        <div class="card-basket-infos">
          <div class="card-basket-stock" style="text-align: center">
         <%= basket.stock %>
          </div>
                   <br>         <br>    <br>
          <div class="card-basket-stock">
         <%= link_to "+", update_stock_path(:stock_update => "increase", :basket_id => basket.id), class: "btn btn-basket-stock"
           %>

          <%= link_to "-", update_stock_path(:stock_update => "decrease", :basket_id => basket.id), class: "btn btn-basket-stock"
           %>

         </div>
        </div>
        <div class="card-basket-infos">
        <%= link_to restaurant_basket_path(params[:restaurant_id], basket.id), class: "btn btn-basket", method: :delete do %>
                Delete basket
          <% end %>
        </div>


    </div>
<br>

  <% end %>
<br>
    <%= link_to "Dashboard", dashboard_path, class: "btn btn-flat", style: "margin-bottom:100px, background: #D94630;" %>

  <%= link_to "Add a basket", new_restaurant_basket_path(@restaurant.id), class: "btn btn-flat", style: "margin-bottom:100px, background: #D94630;" %>

</div>

app/views/baskets/new.html.erb
<%= render 'shared/navbar', new_restaurant: @new_restaurant %>

<div class="container">

<h1>Add a new basket to my restaurant</h1>

<p>This food is going to be wasted! Let's sell a discounted basket of products.</p>

    <%= simple_form_for([@restaurant, @basket]) do |f| %>
        <%= f.input :photo, as: :file, :label=>"Photo:" %>
        <%= f.input :name %>
        <%= f.association :products, :label=>"Products:", as: :check_boxes %>
        <%= f.input :price, :label=>"Price:" %>
        <%= f.input :description, :label=>"Description:" %>
        <%= f.input :stock, :label=>"Stock:" %>

        <%=f.submit%>
  <%end%>

</div>

app/views/baskets/show.html.erb
<h1>Baskets#show</h1>
<p>Find me in app/views/baskets/show.html.erb</p>

  <div class="card-basket">
    <%= cl_image_tag @basket.photo.key, height: 300, width: 400, crop: :fill %>
    <div class="card-basket-infos">
    <%= basket.name %>
    <%= basket.basket_products %>
    <%= basket.description %>
    </div>
</div>

app/views/baskets/update.html.erb
<h1>Baskets#update</h1>
<p>Find me in app/views/baskets/update.html.erb</p>