config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  devise_for :users

  resources :restaurants do
    resources :baskets do
      resources :order_baskets, only: [:create, :destroy]
    end
    resources :products
  end

  resources :orders, only: [:show]

  get 'update_stock', to: 'baskets#update_stock', as: 'update_stock'

  get 'dashboard', to: 'restaurants#dashboard', as: 'dashboard'

end

app/views/shared/_carousel.html.erb
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://cdn.psychologytoday.com/sites/default/files/field_blog_entry_images/2019-06/howcuttingdo.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://berlinfoodstories.com/wp-content/uploads/2020/02/Barra-Berlin-Neukolln-Restaurant-Feature-Food-1000x350.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_map.html.erb
<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/restaurants", class: "navbar-brand" do %>
    <%= image_tag "https://static.thenounproject.com/png/1911779-200.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!--   <div id="navbar-title">
    <h3 class="navbar-name">Zero Food Waste</h3>
  </div> -->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% unless controller_name == "restaurants" && action_name == "index"  %>
         <li class="nav-item">
           <%= link_to "Home", "/", class: "btn btn-flat", id: "HomeButton" %>
         </li>
       <% end %>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= button_tag "Menu", class: "btn btn-flat", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div id="dropdown" class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <p class="dropdown-item" >
              <%= link_to 'Dashboard', dashboard_path, class: "dropdown-item" %>
            </p>
            <% if policy(Restaurant).create? %>
              <p class="dropdown-item" >
                <button type="button" data-toggle="modal" data-target="#exampleModalCenter">New restaurant</button>
              </p>
            <% end %>
            <p class="dropdown-item" >
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </p>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-flat" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-flat" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<%= render partial: 'restaurants/modal', new_restaurant: @new_restaurant %>

app/views/shared/_search.html.erb
<%= form_tag restaurants_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control-index",
    placeholder: "  Find a restaurant..."
  %>
  <%= button_tag class: 'search-btn' do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>

app/views/shared/_tabs.html.erb
<div class="card">
  <div class="card-header no-border bg-white pb-0">

    <ul class="nav nav-pills lavalamp mb-2" id="alert-tab" role="tablist"><div class="lavalamp-object ease" style="transition-duration: 0.2s; width: 69.5625px; height: 37px; transform: translate(2px, 2px);"></div>
      <li class="nav-item lavalamp-item" style="z-index: 5; position: relative;">
        <a class="nav-link active show" id="alert-html-tab" data-toggle="pill" href="#alert-html" role="tab" aria-controls="alert-html" aria-selected="true" onclick="return false">html</a>
      </li>
      <li class="nav-item lavalamp-item" style="z-index: 5; position: relative;">
        <a class="nav-link show" id="alert-css-tab" data-toggle="pill" href="#alert-css" role="tab" aria-controls="alert-css" aria-selected="false" onclick="return false">css</a>
      </li>
    </ul>

  </div>
  <div class="card-body">
    <div class="tab-content" id="alert-tabContent">
      <div class="tab-pane fade active show" id="alert-html" role="tabpanel" aria-labelledby="alert-html-tab">

      </div>

      <div class="tab-pane fade" id="alert-css" role="tabpanel" aria-labelledby="alert-css-tab">

      </div>
    </div>
  </div>
</div>