config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  devise_for :users

  resources :restaurants do
    resources :baskets do
      resources :order_baskets, only: [:create, :destroy]
    end
    resources :products
  end

  resources :orders, only: [:show]

  get 'update_stock', to: 'baskets#update_stock', as: 'update_stock'

  get 'dashboard', to: 'restaurants#dashboard', as: 'dashboard'

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :baskets
  has_many :products
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_category,
    against: [ :name, :category ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/restaurants_controller.rb
  class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  skip_after_action :verify_authorized, only:[:it]

  def index
    @restaurants = policy_scope(Restaurant).order(created_at: :asc)

    if params[:query]
      @restaurants = Restaurant.search_by_name_and_category(params[:query])
    else
      @restaurants = Restaurant.all
    end

    # @restaurants = Restaurant.geocoded # returns restaurants with coordinates
    @markers = @restaurants.map do |restaurant|
      [{
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant })
      }]
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant

    @markers = [{
        lat: @restaurant.latitude,
        lng: @restaurant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: @restaurant })
    }]

    @baskets = []
    @restaurant.basket_ids.each do |id|
      @baskets << Basket.find(id)
    end

    @basket_order = OrderBasket.new

    @cart_baskets = current_user.orders.last.order_baskets
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @restaurant = Restaurant.new(params_restaurant)
    @restaurant.user = current_user
    authorize @restaurant

    if @restaurant.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.update(params_restaurant)
    redirect_to dashboard_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.destroy
    redirect_to dashboard_path
  end

  def dashboard
      @restaurants = Restaurant.where(user_id: current_user)
      authorize @restaurants
  end

  private

  def params_restaurant
    params.require(:restaurant).permit(:name,:description,:address, :category, :price_range, :rating, :photo)
  end
end

app/views/restaurants/_info_window.html.erb
<h2><%= restaurant.name %></h2>
<p><%= restaurant.address %></p>
<p><%= link_to "View restaurant page", restaurant_path(restaurant) %></p>

app/views/restaurants/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter"  role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
    <%= simple_form_for(@new_restaurant) do |f| %>
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">New Restaurant</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= f.input :photo, as: :file %>
        <%= f.input :name, :label=>"Restaurant name" %>
        <%= f.input :description, :label=>"Restaurant description" %>
        <%= f.input :address, :label=>"Restaurant address" %>
        <%= f.input :category, :label=>"Food category" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%=f.submit%>
      </div>
    </div>
  </div>
  <%end%>
</div>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/dashboard.html.erb
<%= render 'shared/navbar', new_restaurant: @new_restaurant %>
<div class="container">
<h1>Restaurant dashboard</h1>



    <% @restaurants.each do |restaurant| %>
      <div class="card-dashboard">
          <div class="card-dashboard-infos">
            <%=link_to restaurant_path(restaurant.id) do %>
              <% if restaurant.photo.attached? %>
            <div class="img">
              <%= cl_image_tag restaurant.photo.key %>
            </div>
              <% else %>
            <div class="img">
              <%= cl_image_tag "https://res.cloudinary.com/dnie1qfbq/image/upload/v1582631708/samples/food/pot-mussels.jpg", height: 300, width: 400, crop: :fill %>
            </div>
              <% end %>
            <% end %>
          </div>


         <div class="card-dashboard-infos-text">
           <%= link_to restaurant_path(restaurant.id) do %>
            <h2><%= restaurant.name %></h2>
              <% end %>
            <p class="myrestaurant-description"><%= restaurant.description %></p>
          </div>

         <div class="card-dashboard-infos">

            <% if policy(restaurant).edit? %>
             <%= link_to edit_restaurant_path(restaurant.id) do %>
             <h3 class="btn-dashboard">Edit restaurant</h3>
            <% end %>
            <% end %>

            <% if policy(restaurant).destroy? %>
              <%= link_to restaurant_path(restaurant.id), method: :delete do %>
              <h3 class="btn-dashboard">Delete restaurant</h3>
              <% end %>
              <%end%>

          </div>

         <div class="card-dashboard-infos">
             <%= link_to restaurant_baskets_path(restaurant.id) do %>
              <h3 class="btn-dashboard">Existing baskets</h3>
                  <% end %>

            <%= link_to new_restaurant_basket_path(restaurant.id) do %>
              <h3 class="btn-dashboard">Add a basket</h3>
                  <% end %>
          </div>

         <div class="card-dashboard-infos">
            <%= link_to restaurant_products_path(restaurant.id) do %>
              <h3 class="btn-dashboard"><%= restaurant.name %> products</h3>
                  <% end %>

            <%= link_to new_restaurant_product_path(restaurant.id) do %>
              <h3 class="btn-dashboard">Add a product</h3>
                  <% end %>
          </div>

        </div>
        <br>
    <%end%>
  </div>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<%= render 'shared/navbar', new_restaurant: @new_restaurant %>
  <div class="container">
    <%= simple_form_for(@restaurant) do |f| %>

        <%= f.input :photo, as: :file, :label=>"Restaurant picture:" %>
        <%= f.input :name, :label=>"Restaurant name:" %>
        <%= f.input :description, :label=>"Restaurant description:" %>
        <%= f.input :address, :label=>"Restaurant address:" %>
        <%= f.input :category, :label=>"Food category:" %>

        <%=f.submit "Edit my restaurant" %>
  <%end%>
  </div>

app/views/restaurants/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(255,255,255,0.2),rgba(255,255,255,0.1)), url(https://images.unsplash.com/photo-1514516870926-20598973e480?ixlib=rb-1.2.1&auto=format&fit=crop&w=1972&q=80);">
  <%= render 'shared/navbar', new_restaurant: @new_restaurant %>
  <div class="container">
    <h1 style="color: #E16B33"><strong style="color: #495773">ZERO</strong> Food to Waste</h1>
    <p>Save money and the environment all in one meal!</p>
    <%= render 'shared/search' %>
  </div>
</div>
<!-- <h2 style="text-align: center">Showing restaurants near Rua Conde Redondo <p style="display: inline; font-size: 18px"><%= link_to "(Change)", edit_user_registration_path %></p></h2>
 --><div class="card">
  <h2 class="card-container-title"><strong>Available today</strong></h2>
  <!-- Start of tabs -->
  <div id ="view" class="card-header no-border pb-0">
    <ul class="nav nav-pills lavalamp mb-2" id="alert-tab" role="tablist">
      <li class="nav-item lavalamp-item" style="z-index: 5; position: relative;">
        <a class="nav-link active show" id="alert-html-tab" data-toggle="pill" href="#alert-html" role="tab" aria-controls="alert-html" aria-selected="true" onclick="return false">List view</a>
      </li>
      <li class="nav-item lavalamp-item" style="z-index: 5; position: relative;">
        <a class="nav-link show" id="alert-css-tab" data-toggle="pill" href="#alert-css" role="tab" aria-controls="alert-css" aria-selected="false" onclick="return false">Map view</a>
      </li>
    </ul>
  </div>
  <!-- End of tabs -->
  <div class="card-body">
    <div class="tab-content" id="alert-tabContent">
      <div class="tab-pane fade active show" id="alert-html" role="tabpanel" aria-labelledby="alert-html-tab">
        <!-- Restaurant cards tab: -->
        <div class="cards">
        <% @restaurants.each do |restaurant| %>
        <%= link_to restaurant_path(restaurant), class: "resto-card" do %>
          <div class="card-trip">
           <% if restaurant.photo.attached? %>
              <%= cl_image_tag restaurant.photo.key %>
              <% else %>
              <%= cl_image_tag "https://res.cloudinary.com/dnie1qfbq/image/upload/v1582631708/samples/food/pot-mussels.jpg", height: 300, width: 400, crop: :fill %>
              <% end %>
            <div class="card-trip-infos">
              <div>
                <h2 class='restaurant-name'><%= restaurant.name %></h2>
                <p> <%= restaurant.description[0..100]... %></p>
              </div>
              <% unprice = 3 - restaurant.price_range.to_s.length %>
              <h2 class="card-trip-pricing" style="color: #F2C94C">
                <%= restaurant.price_range %>
                <% unprice.times do %>
                  <h2 style="display:inline; color: #F0EBE5">$</h2>
                <% end %>
              </h2>
            </div>
            <div class="card-specifics">
              <p class="specific"><i class="fas fa-utensils" style="color: #D94630"></i> <%= restaurant.category %></p>
              <p class="specific"><i class="fas fa-map-marker-alt" style="color: #D94630"></i> <%= restaurant.address %></p>
              <p class="specific"><i class="fas fa-star" style="color: #F2C94C; text-shadow: 1px 1px 1px gray"></i> <%= restaurant.rating %>/5</p>
            </div>
          </div>
          <% end %>
        <% end %>
        </div>
        <!-- End of restaurant cards -->
      </div>
      <div class="tab-pane fade" id="alert-css" role="tabpanel" aria-labelledby="alert-css-tab">
        <!-- Map tab: -->
        <div class="mapview-container">
          <div class="card-list">
            <% @restaurants.each do |restaurant| %>
              <%= link_to restaurant_path(restaurant), class: "resto-card" do %>
                <div class="card-product">
                  <div class="img-title">
                    <div class="card-product-img">
                    <img src="https://berlinfoodstories.com/wp-content/uploads/2020/02/Barra-Berlin-Neukolln-Restaurant-Feature-Food-1000x350.jpg"/>
                    </div>
                    <div class="card-product-infos">
                      <h2 class="product-title"><%= restaurant.name %></h2>
                      <p>Product description with <strong>relevant info</strong> only.</p>
                    </div>
                  </div>
                  <div class="card-product-specifics">
                    <p class="product-specific">
                      <% if restaurant.rating.nil? %>
                        <% "No rating for now" %>
                      <% else %>
                        <% unstar = 5 - restaurant.rating %>
                        <% restaurant.rating.times do %>
                          <i class="fas fa-star" style="color: #FEC739; text-shadow: 1px 1px gray;"></i>
                        <% end %>
                        <% unstar.times do %>
                          <i class="fas fa-star" style="color: #FEC739; display:inline; color: #F0EBE5"></i>
                        <% end %>
                      <% end %>
                    </p>
                    <p class="product-specific"><i class="fas fa-utensils" style="color: #D94630"></i> <%= restaurant.category %></p>
                    <p class="product-specific"><i class="fas fa-map-marker-alt" style="color: #D94630"></i> <%= restaurant.address %></p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
          <div
            id="map"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          ></div>
        </div>
        <!-- End of map tab -->
      </div>
    </div>
  </div>
</div>


<script>
 const target = document.getElementById('alert-css-tab');
  const target2 = document.getElementById('alert-html-tab');

console.log(target);
 target.addEventListener("click", (event) => {
 // event.currentTarget.classList.toggle("orange");
 target.className = "nav-link show orange";
 target2.className = "nav-link show";

 // target2.currentTarget.classList.toggle("orange");
});

  target2.addEventListener("click", (event) => {
  target2.className = "nav-link show orange";
  target.className = "nav-link show";

});
</script>

app/views/restaurants/new.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
  New restaurant
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
    <%= simple_form_for(@restaurant) do |f| %>
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Create a Restaurant</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= f.input :photo, as: :file, :label=>"Photo:" %>
        <%= f.input :name %>
        <%= f.input :description, :label=>"Restaurant description:" %>
        <%= f.input :address %>
        <%= f.input :category %>
        <%= f.input :price_range , :label=>"Price discounted" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%=f.submit%>
      </div>
    </div>
  </div>
  <%end%>
</div>

app/views/restaurants/show.html.erb
<%= render 'shared/navbar', new_restaurant: @new_restaurant %>


<div class="banner-container">

  <div class="rest-banner">
    <img src="https://berlinfoodstories.com/wp-content/uploads/2020/02/Barra-Berlin-Neukolln-Restaurant-Feature-Food-1000x350.jpg" />
  </div>

</div>

<div class="show-body">
  <div class="title-address">

    <div class="title-info">
      <h1><%= @restaurant.name %></h1>
      <p>
        <i class="fas fa-utensils" style="color: #D94630"></i> <%= @restaurant.category %>
        <% if @restaurant.rating.nil? %>
          <% "No rating for now" %>
        <% else %>
          <% unstar = 5 - @restaurant.rating %>
          <% @restaurant.rating.times do %>
            <i class="fas fa-star" style="color: #FEC739; text-shadow: 1px 1px gray;"></i>
          <% end %>
          <% unstar.times do %>
            <i class="fas fa-star" style="display:inline; color: #DDDDDD"></i>
          <% end %>
        <% end %>
      </p>
    </div>

    <div class="address-info">
      <h3><i class="fas fa-map-marker-alt" style="color: #D94630"></i> <%= @restaurant.address %></h3>
      <p>Insert distance from user location here</p>
    </div>
  </div>
</div>

<div class="description">
  <div class="all-content">
    <div class="content-box">   <!-- Start of content box -->
      <div class="info-and-map">
        <div class="infos">
          <p><%= @restaurant.description %></p>
          <p><i class="fas fa-shopping-bag" style="color: #D94630"></i> At closing time, the employees at <%= @restaurant.name %> will use leftover food items to make baskets.</p>
          <p><i class="fas fa-shopping-bag" style="color: #D94630"></i> The products in these baskets and their availability changes daily.</p>
          <p><i class="fas fa-shopping-bag" style="color: #D94630"></i> At <%= @restaurant.name %> you can expect to find some of the following products: x, y, z.</p>
        </div>

        <div
          id="map"
          style="width: 370px;
          height: 370px;
          border-radius: 4px;
          border: 1px solid lightgray;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>
      </div> <!-- End of info and map -->
    </div>   <!-- End of content box -->

    <div class="bottom-content"> <!-- Start of basket cards -->
      <div class="basket-cards">
        <h2 style="color: #E16B33" class="todays-baskets">Today's baskets:</h2>
        <div class="card-list">
          <% @baskets.each do |basket| %>
            <% if basket.stock > 0 %>
              <div class="card-product">
              <img src="https://res.cloudinary.com/dnie1qfbq/image/upload/v1582631708/samples/food/pot-mussels.jpg" />
              <div class="card-product-infos">
              <h2><%= basket.name %></h2>
              <p><%= basket.description %></p>
              </div>
              <div class="cart-btn">
                <%= link_to "Add to cart", restaurant_basket_order_baskets_path(@restaurant,basket,@order_basket), method: :post, class: "btn btn-flat" %>
              </div>
              </div>
          <% end %>
          <% end %>

        </div>
           </div>
    </div> <!-- End of basket cards -->
  </div> <!-- End of all content -->

  <div class="cart-div">
    <div class="cart">
      <h2>Cart</h2>

      <div class="cart-items">
        <% @cart_baskets.each do |basket| %>
          <div class="card-product">
            <div class="card-product-infos">
              <h2><%= basket.basket.name %></h2>
              <p><%= basket.basket.description %></p>
            </div>
            <% @basket = basket.basket %>
            <div class="remove-btn" style="margin-right: 10px;">
              <%= link_to restaurant_basket_order_basket_path(@restaurant,@basket,basket), method: :delete do %>
                <i class="fas fa-times" style="color: gray"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <%= link_to "Checkout", order_path(current_user.orders.last), class: "btn btn-flat" %>
    </div>
  </div>
</div>

app/views/restaurants/update.html.erb
    <%= simple_form_for(@restaurant) do |f| %>

        <%= f.input :photo, as: :file %>
        <%= f.input :name, :label=>"Restaurant name" %>
        <%= f.input :description, :label=>"Restaurant description" %>
        <%= f.input :address, :label=>"Restaurant address" %>
        <%= f.input :category, :label=>"Food category" %>

        <%=f.submit "Edit my restaurant"%>
  <%end%>