config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  devise_for :users

  resources :restaurants do
    resources :baskets do
      resources :order_baskets, only: [:create, :destroy]
    end
    resources :products
  end

  resources :orders, only: [:show]

  get 'update_stock', to: 'baskets#update_stock', as: 'update_stock'

  get 'dashboard', to: 'restaurants#dashboard', as: 'dashboard'

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :restaurant
  has_many :basket_products, dependent: :destroy
  has_many :baskets, through: :basket_products, dependent: :nullify
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_restaurant, only: [:new,  :create, :destroy]

  def index
    @products = policy_scope(Product).order(created_at: :desc)
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(params_product)
    authorize @product
    @product.restaurant = @restaurant
    if @product.save
      redirect_to restaurant_products_path, notice: "Product #{@product.name} added"
    else
      render :new
    end
  end

  def edit
  end

  def update

  end

  def destroy
    @product = Product.find(params[:id])
    authorize @product
    @product.destroy
    redirect_to restaurant_products_path notice: "Bye bye #{@product.name}"
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def params_product
    params.require(:product).permit(:name, :price, :description)
  end
end

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<%= render 'shared/navbar' %>

<div class="container">
  <h1>Products</h1>


  <% @products.each do |product| %>
    <div class="card-product">
      <img src="https://res.cloudinary.com/dnie1qfbq/image/upload/v1582631707/samples/food/dessert.jpg" />
        <div class="card-product-infos">
        <h2><%= product.name %></h2>
         <p><%= product.description %></p>
         <p><%= product.price %>€</p>
         <%= link_to restaurant_product_path(params[:restaurant_id], product.id), method: :delete do %>
                <h3 class="btn btn-default" >Delete <%= product.name %></h3>
          <% end %>
        </div>
     </div>
     <br>
    <% end %>

  <br>

  <%= link_to "Dashboard", dashboard_path, class: "btn btn-flat", style: "margin-bottom:100px, background: #D94630;" %>

  <%= link_to "Add product", new_restaurant_product_path(@restaurant.id), class: "btn btn-flat", style: "margin-bottom:100px, background: #D94630;" %>


</div>

app/views/products/new.html.erb
<%= render 'shared/navbar', new_restaurant: @new_restaurant %>

<h1>Add a new product to your restaurant</h1>

    <%= simple_form_for([@restaurant, @product]) do |f| %>

        <%= image_tag("https://res.cloudinary.com/dnie1qfbq/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1582631707/samples/food/dessert.jpg", class: "imagenewproduct", :width=>300, :height=>300, :crop=>"scale") %>
        <%= f.input :name %>
        <%= f.input :price %>
        <%= f.input :description %>
        <%=f.submit%>
  <%end%>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>